### ISSUE TITLE
403 error when trying to access api.get_characters()

### ISSUE THREAD

**Issue by godlike64** [lockwooddev/python-wowapi#15]
Hi, I'm starting to toy around with python-wowapi and testing some stuff. However, I cannot seem to get some endpoints to work. Namely get_characters() (but I would believe others would be affected).

My code:

~~~
>>> from wowapi import WowApi
>>> api = WowApi('CLIENT_ID', 'CLIENT_SECRET')
>>> api.get_characters('us')
Fetching access token..
Fetching new token from: https://us.battle.net/oauth/token?grant_type=client_credentials&client_id=CLIENT_ID&client_secret=CLIENT_SECRET
New token ACCESS_TOKEN expires at 2019-10-02 14:59:08.140700 UTC
Requesting resource: https://us.api.blizzard.com/wow/user/characters with parameters: {'access_token': 'ACCESS_TOKEN'}
Invalid response - https://us.api.blizzard.com/wow/user/characters - 403
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/godlike/sandbox/python-wowapi/wowapi/mixins/community.py", line 160, in get_characters
    return self.get_resource('wow/user/characters', region, **filters)
  File "/home/godlike/sandbox/python-wowapi/wowapi/api.py", line 161, in get_resource
    return self._handle_request(url, region, params=filters)
  File "/home/godlike/sandbox/python-wowapi/wowapi/api.py", line 128, in _handle_request
    raise WowApiException(msg)
wowapi.exceptions.WowApiException: Invalid response - https://us.api.blizzard.com/wow/user/characters - 403
~~~

However, other endpoints (public ones maybe?) work just fine:

~~~
>>> api.get_character_profile('us', 'kel\'thuzad', 'Stilgan')
Requesting resource: https://us.api.blizzard.com/wow/character/kel'thuzad/Stilgan with parameters: {'access_token': 'ACCESS_TOKEN'}
{'lastModified': 1569896706000, 'name': 'Stilgan', 'realm': "Kel'Thuzad", 'battlegroup': 'Vindication', 'class': 8, 'race': 11, 'gender': 0, 'level': 120, 'achievementPoints': 12530, 'thumbnail': 'kelthuzad/116/174610804-avatar.jpg', 'calcClass': 'e', 'faction': 0, 'totalHonorableKills': 268}
>>> 
~~~

Am I doing something wrong? I didn't see if there was any caveat in the documentation, but after tweaking the logging a little bit, the library does appear to be following the correct Oauth flow.

Just to double check, I am able to use the API via https://develop.battle.net/documentation/api-reference/world-of-warcraft-community-api using my client_id and client_secret.

**Comment by lockwooddev** [comment]
Hi,

Thanks for your ticket. I did some digging and apparently I overlooked that the `wow/user/characters` endpoint not using _client credential flow_, but _authorization code flow_ to get a valid token. 

https://develop.battle.net/documentation/guides/using-oauth/authorization-code-flow

Now considering that _authorization code flow_ requires an application server and also a web browser, I will have to remove this endpoint, or at least make it accept the token resulting from this OAuth flow.

Sorry for this inconvenience, let me know however what you think and if you find any more endpoints not working.

**Comment by godlike64** [comment]
Well, my original idea behind using this API was to eventually make a web application for this, so although i don't particularly like thatoauth part, it's going to have to make do.

Does python-wowapi support that type of oauth flow? If so could you point me to the docs on how to do this?

**Comment by lockwooddev** [comment]
I designed python-wowapi to only support the client credential flow. This is what blizzard supports for backend to backend API calls.

You can still use python-wowapi in your backend for other calls, but will have to make an exception for the character endpoint, since it really only works with web browsers.

The token eventually returned can be passed to `WowApi.get_characters` `**filters` as `access_token`, but you will have to implement code authorization flow yourself.

**Comment by lockwooddev** [comment]
This is how to get the access_token https://develop.battle.net/documentation/guides/using-oauth/authorization-code-flow

**Comment by godlike64** [comment]
Roger that, thanks!

**Comment by godlike64** [comment]
Sorry for bothering again (I wouldn't want to make these type of questions on a GH issue, but then again GH does not have a way of DMing someone :P), but do you know if there are other endpoints which would require the auth flow instead of the client credential flow?

e.g. I was trying to access the /wow/character/feed/, which isn't mapped, so I tried to add it to wowapi/mixins/profile.py:

~~~
    def get_character_feed(
        self, region, namespace, realm_slug, character_name, **filters
    ):
        """
        Character Achievements API
        Returns a summary of the achievements a character has completed
        """
        filters['namespace'] = namespace
        resource = 'profile/wow/character/{0}/{1}/feed'
        return self.get_resource(resource, region, *[realm_slug, character_name], **filters)
~~~

This also failed with a 403. Tried:

~~~
        return self.get_resource(resource, region, *[realm_slug, character_name], fields='feed', **filters)
~~~

as well as reverting that and calling via:

~~~
>>> api.get_character_feed('us', 'dynamic-us', 'kel\'thuzad', 'stilgan', fields='feed')
~~~

I also tried adding this after filters['namespace']:

~~~
filters['fields'] = 'feed'
~~~

In all cases I get a 403 similar to the one I mentioned when opening this issue. This endpoint does not show up in the page about the auth flow.

After taking a closer read at the other examples in the profile.py, I tried get_character_stats_summary(), same results:

~~~
>>> api.get_character_stats_summary('us', 'dynamic-us', 'kel\'thuzad', 'stilgan')
Requesting resource: https://us.api.blizzard.com/profile/wow/character/kel'thuzad/stilgan/statistics with parameters: {'namespace': 'dynamic-us', 'access_token': ACCESS_TOKEN}
Invalid response - https://us.api.blizzard.com/profile/wow/character/kel'thuzad/stilgan/statistics - 403
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/godlike/sandbox/python-wowapi/wowapi/mixins/profile.py", line 111, in get_character_stats_summary
    return self.get_resource(resource, region, *params, **filters)
  File "/home/godlike/sandbox/python-wowapi/wowapi/api.py", line 161, in get_resource
    return self._handle_request(url, region, params=filters)
  File "/home/godlike/sandbox/python-wowapi/wowapi/api.py", line 128, in _handle_request
    raise WowApiException(msg)
wowapi.exceptions.WowApiException: Invalid response - https://us.api.blizzard.com/profile/wow/character/kel'thuzad/stilgan/statistics - 403
>>> 
~~~

Would this point to all of /wow/character/ to be requiring the auth flow? I wish Blizzard's docs would be clearer on this if that was the case.

**Comment by lockwooddev** [comment]
No problem :)

I tried looking for `/wow/character/feed/`, but I don't think it even exists. I think you're looking for:
`api.get_character_profile('us', "Kel'Thuzad", 'asmongold', fields='feed')`

`get_character_stats_summary` doesn't allow for `dynamic-us`. Use instead the `profile-{region}` namespace.
`api.get_character_stats_summary('us', 'profile-us', "kelthuzad", 'asmongold')`
(see [here](https://develop.battle.net/documentation/guides/game-data-apis-wow-namespaces) about namespaces)

It's incorrect however from Blizzard to throw a 403 for this. A 400 would be more appropriate.

**Comment by godlike64** [comment]
Ah, thanks for that, i am still trying to find my way around the API. I will try that shortly, although it does seem Blizzard will soon change the API and this specific field/endpoint will be removed:

~~~
This endpoint is being migrated off of the Community API. For more information, see World of Warcraft Community API Migration Status.
~~~

https://develop.battle.net/documentation/guides/community-apis-world-of-warcraft-community-api-migration-status

I could swear that warning was not there yesterday, but it looks like the Community API will be no more? Doesn't look like they will move most stuff behind oauth auth flow, but some endpoints/fields are already deprecated (feed included) and will be removed.

**Comment by lockwooddev** [comment]
Funny I never knew about https://develop.battle.net/documentation/guides/community-apis-world-of-warcraft-community-api-migration-status

Looks indeed like the community api will be killed off. I will need to make sure the game data endpoints stay up to date.

**Comment by godlike64** [comment]
Yes, some endpoints/fields will be deprecated sadly. Anyway, glad I could be of some healp at least haha :) Thanks!

**Comment by lockwooddev** [comment]
Thanks for the ticket. You made me aware of the deprecation schedule. Let me know if you have more issues in the future with this library :)
