### ISSUE TITLE
Allow get_data_resource to accept filters (i.e. locale)

### ISSUE THREAD

**Issue by clegg89** [lockwooddev/python-wowapi#16]
At the moment, `get_data_resource` accepts only url and region. It would be useful to accept `filters` as other api calls do to allow for adding things like `locale` to url's obtained from the game-data API:

```python
race = api.get_playable_race_index('us', 'static-us', locale='en_US')
human = api.get_data_resource(race['races'][0]['key']['href'], 'us', locale='en_US')
```

**Comment by lockwooddev** [comment]
@clegg89 4.0.0 `get_data_resource` now supports filters
