### ISSUE TITLE
Community API retired - Game Data missing APIs

### ISSUE THREAD

**Issue by tehmufifnman** [lockwooddev/python-wowapi#17]
Hiya  lockwooddev!

Do you plan on updating this with the recent drastic changes in Blizzard's API.

Community API has been completely retired.
Game Data API has added several endpoints, for example an Auction House endpoint that is very different than its old Community API endpoint.

Also one thing to note, with the new Auction House API specifically, we need an option to make a head() only request (no content) to the endpoint.  The "last modified" date/time of Auction House data is stored there.  Currently this package only returns the JSON from the response.

I was tinkering with some of these changes in a branch but I didn't want to waste time if you were also working on some changes!

If you don't plan on continuing this project, please let me know - I would gladly adopt it.

Thanks for all your work on this, I hope this message finds you safe!

**Comment by lockwooddev** [comment]
Hi,

I do plan on continuing with this project. I've already started the migration, but then came the corona lockdown in my country (1 month already) and I failed to make the migration deadline. I'm locked up with my kids and have little energy at the moment to continue with the changes.

Let me know if you want to contribute and I will review the changes with you.

**Comment by lockwooddev** [comment]
@tehmufifnman Try out 4.0.0 it has the updated endpoints from Blizzards march API deprecations.
