### ISSUE TITLE
Parse JSON into Python Classes

### ISSUE THREAD

**Issue by kvosbur** [lockwooddev/python-wowapi#19]
It would be nice if the json was parsed into python class models. This would allow for better navigation of the data especially within IDEs. I know this would take a decent amount of work, but it would definitely make it nicer. I would be willing to put some time into making this happen.

**Comment by lockwooddev** [comment]
It would not only give you more work, but also add more maintenance. Blizzard changes their API's constantly. It would be wiser to wait for them to release an open api spec.

If you really need to parse into python classes, you can always do it on your side from the json. I'm very much on the fence with this.

**Comment by kvosbur** [comment]
Yeah I think I am starting to see what you mean as I am starting to work with the result data. Their api isn't quite as nice for some stuff as I thought it would be.

**Comment by lockwooddev** [comment]
The api results used to be better in the past, but it has become worse over the years with their over the top RESTful approach. Good luck with your implementation :)
