### ISSUE TITLE
Old API discontinued

### ISSUE THREAD

**Issue by crmhaske** [lockwooddev/python-wowapi#2]
Will this be updated in light of changes to API access:

http://us.battle.net/forums/en/bnet/topic/19496980106

**Comment by lockwooddev** [comment]
Thanks for letting me know. This ticket was unfortunately buried in my notifications. I'm refactoring the api wrapper and hope to release a new version soon.

**Comment by lockwooddev** [comment]
https://github.com/lockwooddev/python-wowapi/tree/1.0
