### ISSUE TITLE
GameData not working, develop.battle.net not working. Is there somewhere something that is working?

### ISSUE THREAD

**Issue by Izzy3110** [lockwooddev/python-wowapi#24]
Sry, but I think blizz needs more developers, or even more with brain. I myself test my code before i publish sth. :D
gamedata.py - not working, nothing is working :D throw your computer in trash, go get a gameboy and play pokemon, but don't dev anymore, THANK YOU

**Comment by lockwooddev** [comment]
Hi, you should direct your feedback at blizzard. They keep changing the API endlessly and are too lazy to provide an auto generated client for many languages. I can't keep up with all the changes and you are welcome to contribute to this project.
