### ISSUE TITLE
Getting guild members

### ISSUE THREAD

**Issue by MotherGinger** [lockwooddev/python-wowapi#3]
It doesn't look like there is a method for getting guild members e.g. `WowApi.get_guild_members()`

I am able to make this request manually, however it would be nice to keep all my calls contained to your module if possible.

If I get some time maybe I can submit a PR if that is faster.

Great module btw!

**Comment by lockwooddev** [comment]
Looks like blizzard did some updates or I missed an endpoint. 

I will update the library soon for you. Probably this weekend, due to work.

Thank you for using my library!

**Comment by lockwooddev** [comment]
Let me know if this works for you.
