### ISSUE TITLE
get wow_token price

### ISSUE THREAD

**Issue by litolite** [lockwooddev/python-wowapi#5]
Hello, implement get_wowtoken_price. I wrote it in my downloaded api.py, but i think this is crutch.
def get_resource(self, resource, region, type=None, *args, **filters):
        resource = resource.format(*args)

        base_url = self.__base_url.format(region)
        if region == 'cn':
            base_url = 'api.blizzard.com.cn'
        if type == 'token':
            base_url +=  '/data'

**Comment by lockwooddev** [comment]
Hi,

I did not implement the Game Data API yet. This library currently only covers the Community API. Historically the two API's were separate and the authentication process they used. Now that both API's use client credential flow, it should not be an issue to support the Game Data API as well. However I do have a full time job and my time is limited. PR's are welcome of course.

**Comment by lockwooddev** [comment]
I added game data api support if it's still relevant for you. Check out how to use the new methods in the readme. Let me know if you have issues.

#6
