### ISSUE TITLE
Error when using get_data_resource

### ISSUE THREAD

**Issue by tehmufifnman** [lockwooddev/python-wowapi#9]
This issue seems to happen randomly/intermittently.  I can run my script and it will work fine and then wait a minute before running it again and this error is produced.  Any clue?  I am on the most recently version.

The relevant code is this:
```
self._wowapi = WowApi(CLIENT_ID, CLIENT_SECRET)
self._auction_header = self._wowapi.get_auctions(self._region_prefix, self._realm_slug, locale='en_US')
data_url = self._auction_header['files'][0]['url']
self._auction_data = self._wowapi.get_data_resource(data_url, self._region_prefix)
```

> Traceback (most recent call last):
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
>     response.begin()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
>     version, status, reason = self._read_status()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\util\retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
>     response.begin()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
>     version, status, reason = self._read_status()
>   File "C:\Users\Muffin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\wowapi\api.py", line 74, in _handle_request
>     response = self._session.get(url, **kwargs)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\requests\sessions.py", line 546, in get
>     return self.request('GET', url, **kwargs)
>   File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\requests\sessions.py", line 533, in request

**Comment by lockwooddev** [comment]
Hi. This is more or less a problem at Blizzards end. The only things I can do is to catch the exception or modify the http adapter to retry x times. In the meantime you can catch the exception and handle the retry yourself.

**Comment by tehmufifnman** [comment]
> 
> 
> Hi. This is more or less a problem at Blizzards end. The only things I can do is to catch the exception or modify the http adapter to retry x times. In the meantime you can catch the exception and handle the retry yourself.

LOL - Ya that sounds about right for Blizzard.  Thanks!

**Comment by tehmufifnman** [comment]
Also seem to be getting occasional failures when trying to get a new token.

> File "E:\Dropbox\Projects\TradeSkillMaster\PyBackend\env\lib\site-packages\wowapi\api.py", line 45, in _get_client_credentials
> wowapi.exceptions.WowApiOauthException: HTTPSConnectionPool(host='eu.battle.net', port=443): Max retries exceeded with url: /oauth/token?grant_type=client_credentials&client_id=45a0250fa0d749509a238f05aab30a81&client_secret=ZZ47Af1jrUKlYp1m3OXgyygsGyWLMRIj (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CB20512908>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by lockwooddev** [comment]
Same as the above. You will need to retry. Unfortunately I'm not in charge of Blizzards servers or internet connection 😸
